{{- if .Values.autoscaling.enabled }}
---
{{- if .Values.api.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nanovia.fullname" . }}-api-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nanovia.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nanovia.fullname" . }}-api
  minReplicas: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.api.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.memoryUtilization }}
{{- end }}
---
{{- if .Values.web.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nanovia.fullname" . }}-web-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nanovia.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nanovia.fullname" . }}-web
  minReplicas: {{ .Values.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.web.cpuUtilization }}
{{- end }}
---
{{- if .Values.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nanovia.fullname" . }}-worker-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nanovia.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nanovia.fullname" . }}-worker
  minReplicas: {{ .Values.autoscaling.worker.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.worker.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.worker.cpuUtilization }}
{{- end }}
{{- end }}
