{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nanovia.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nanovia.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
        - {{ .Values.ingress.apiDomain }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nanovia.fullname" . }}-web
                port:
                  number: 80
    - host: {{ .Values.ingress.apiDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nanovia.fullname" . }}-api
                port:
                  number: 80
{{- end }}
