{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nanovia.fullname" . }}-api-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nanovia.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app: {{ include "nanovia.fullname" . }}-api
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
{{- end }}
{{- end }}
