apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: nanovia
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
