apiVersion: v1
kind: ConfigMap
metadata:
  name: nanovia-config
  namespace: nanovia
  labels:
    app.kubernetes.io/name: nanovia
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: kustomize
data:
  APP_ENV: "production"
  APP_NAME: "Nanovia OS"
  APP_REGION: "eu-west-1"
  REDIS_URL: "redis://redis:6379/0"
  API_HOST: "0.0.0.0"
  API_PORT: "8010"
  LOG_LEVEL: "INFO"
  SCRAPING_ENABLED: "false"
  SCRAPING_STEALTH_MODE: "false"
  CHAOS_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
