apiVersion: v1
kind: Service
metadata:
  name: nanovia-api-green
  namespace: nanovia
  labels:
    app.kubernetes.io/name: nanovia-api-green
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app: nanovia-api
    version: green
  ports:
    - name: http
      port: 80
      targetPort: 8010
