apiVersion: v1
kind: ConfigMap
metadata:
  name: nanovia-redis-config
  namespace: nanovia
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: kustomize
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    protected-mode no
