apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nanovia
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
